const fs = require('fs');
const path = require('path');

// Read package.json
const packageJson = JSON.parse(fs.readFileSync(path.join(__dirname, '../package.json'), 'utf8'));
const version = packageJson.version;

// Generate version.js content
const versionFileContent = `// This file is automatically generated - DO NOT EDIT
// Generated from package.json version ${version}
export const version = '${version}';\n`;

// Write to version.js
fs.writeFileSync(path.join(__dirname, '../src/version.js'), versionFileContent);

console.log(`✓ Updated src/version.js with version ${version}`); 